name: Actions Build Docker Image
run-name: ${{ gitea.actor }} is building new image 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: soaska
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - name: Install Node.js
        run: |
          apk add --no-cache nodejs
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}          
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Install Docker
        run: |
          apk add --no-cache docker
      - name: Start Docker service
        run: |
          dockerd &
          sleep 5
          docker info          
      - name: Build Dockerfile
        run: |
          docker build -t sd_telegram .          
      - name: Add new variables
        run: |
          package_name=$(basename ${{ github.repository }})
          commit_date=$(git log -1 --format=%cd --date=format:'%Y%m%d%H%M%S')
          echo "package_name=$package_name, commit_date=$commit_date" 
      - name: Upload Docker image to soaska.ru
        run: |
          package_name=$(basename ${{ github.repository }})
          commit_date=$(git log -1 --format=%cd --date=format:'%Y%m%d%H%M%S')
          docker login -u ${{ secrets.username }} -p ${{ secrets.password }} soaska.ru
          docker tag sd_telegram soaska.ru/soaska/$package_name:$commit_date
          docker tag sd_telegram soaska.ru/soaska/$package_name:latest
          docker push soaska.ru/soaska/$package_name:$commit_date
          docker push soaska.ru/soaska/$package_name:latest